apiVersion: v1
kind: Service
metadata:
  name: php-app-nodeport
spec:
  type: NodePort
  selector:
    app: php-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # You can specify a port here or let Kubernetes assign one

