apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_user: dXNlcg== # Replace with base64-encoded username, e.g., echo -n "myuser" | base64
  db_password: dXNlcg==  # Replace with base64-encoded password, e.g., echo -n "mypassword" | base64
  
