apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-configmap
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS my_database;
    USE my_database;
    CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL);
    INSERT INTO users (name) VALUES ('Example Data 1'), ('Example Data 2');

